name: Daily Job Alerts

on:
  schedule:
    - cron: "0 0 * * *"    # 12:00 AM UTC (8 PM previous day EDT)
    - cron: "0 12 * * *"   # 12:00 PM UTC (8 AM EDT)
  workflow_dispatch:       # Optional: allow manual trigger from GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run job alert scraper
      env:
        EMAIL_USER: arijit.chowdhury333@gmail.com
        EMAIL_PASS: tmnmdwhredyjwozr
        EMAIL_TO: arijit.chowdhury333@gmail.com
      run: |
        python main.py

    - name: Commit updated job JSON logs
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add jobsFound/*.json
        git commit -m "Update job logs on $(date)" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
